### ISSUE TITLE
How to generate for custom cloth and person?

### ISSUE THREAD

**Issue by gaurav-95** [jokerlc/RMGN-VITON#2]
Hello, I want to run the model on a custom set of cloth and people. Do I generate masks for the custom data? If so, how do I get the masks that you have generated in the test data?

Or am I missing something else here?

**Comment by jokerlc** [comment]
Yes, the masks of the clothes  are necessary. The masks in the test data are provided by others. But i think you can find any opensouce model for background removing, which can extract the masks of your custom cloth
