### ISSUE TITLE
bad result

### ISSUE THREAD

**Issue by junedwx** [jokerlc/RMGN-VITON#6]
Hi, I ran the test code test.py, but the result was bad. Can you tell me what's wrong?
My input is:  test.py --name paired --resize_or_crop scale_width --batchSize 1 --gpu_ids 0 --predmask
the result like this:
![image](https://user-images.githubusercontent.com/23497386/205255412-6f135bac-999d-4b0b-a61f-775d20d373d5.png)

**Comment by jokerlc** [comment]
which torch version did you use?

**Comment by junedwx** [comment]
> which torch version did you use?

python --> 3.8.5
torch --> 1.7.1
<img width="337" alt="1670235190033" src="https://user-images.githubusercontent.com/23497386/205611472-8d888f89-fa69-477a-b834-ade3f57c80b2.png">

**Comment by jokerlc** [comment]
maybe it's due to the env, you can try update torch to 1.8

**Comment by junedwx** [comment]
> maybe it's due to the env, you can try update torch to 1.8

Thanks for your reply. I upgraded pytorch to 1.10.2, and the results are similar to those in the paper.

I have another question to ask, F.grid and interpolate function : align_corners=True parameter is not set in the current code. Will the result be affected?

warning: /root/miniconda3/lib/python3.8/site-packages/torch/nn/functional.py:3631: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.

**Comment by jokerlc** [comment]
i think it doesn't  affect

**Comment by junedwx** [comment]
> i think it doesn't affect
Thank you for your reply!
