### ISSUE TITLE
Test environment in paper

### ISSUE THREAD

**Issue by zero-nnkn** [jokerlc/RMGN-VITON#8]
![image](https://user-images.githubusercontent.com/60695920/217803482-00073b14-489d-49e0-af9d-77b3f46ed8ae.png)

Hi,
 
Can you give me the details of the test environment in the paper? How can I reproduce the experiments with the public checkpoints?

Thanks!

**Comment by jokerlc** [comment]
python>=3.6
torch>=1.8
cupy-cuda101

https://github.com/jokerlc/RMGN-VITON/issues/6

**Comment by zero-nnkn** [comment]
Thanks for your reply @jokerlc . Did you use the same env for all methods (as ACGPN, PF-AFN) ?

**Comment by jokerlc** [comment]
same with PF-AFN,  ACGPN not sure

**Comment by zero-nnkn** [comment]
Thanks for your reply.
